<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Gruppo', 'default');

/**
 * BaseGruppo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nome
 * @property Doctrine_Collection $UtentiGruppo
 * @property Doctrine_Collection $Utenti
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGruppo extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('gruppo');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nome', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             'fixed' => true,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));

    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('UtenteGruppo as UtentiGruppo', array(
             'local' => 'id',
             'foreign' => 'gruppo_id'));
        
        $this->hasMany('Utente as Utenti', array(
             'refClass' => 'UtenteGruppo',
             'local' => 'gruppo_id',
             'foreign' => 'utente_id'));
        
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($softdelete0);
    }
}