<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Provincia', 'default');

/**
 * BaseProvincia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id
 * @property string $nome
 * @property integer $regione_id
 * @property Regione $Regione
 * @property Doctrine_Collection $Farmacie
 * @property Doctrine_Collection $Microbricks
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProvincia extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('provincia');
        $this->hasColumn('id', 'string', 2, array(
             'type' => 'string',
             'length' => 2,
             'fixed' => true,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('nome', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('regione_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Regione', array(
             'local' => 'regione_id',
             'foreign' => 'id'));

        $this->hasMany('Farmacia as Farmacie', array(
             'local' => 'id',
             'foreign' => 'provincia_id'));

        $this->hasMany('Microbrick as Microbricks', array(
             'local' => 'id',
             'foreign' => 'provincia_id'));
        
        $this->hasMany('Farmacie_attivate_agente_view', array(
             'local' => 'id',
             'foreign' => 'provincia_id'));
        
        $this->hasMany('Farmacie_attivate_advisor_view', array(
             'local' => 'id',
             'foreign' => 'provincia_id'));
    }
}