<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Linea', 'default');

/**
 * BaseLinea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id
 * @property string $descrizione
 * @property Doctrine_Collection $Farmacie
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLinea extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('linea');
        $this->hasColumn('id', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             'fixed' => true,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('descrizione', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Farmacia as Farmacie', array(
             'local' => 'id',
             'foreign' => 'linea_id'));
    }
}