<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Prodotto', 'default');

/**
 * BaseProdotto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nome
 * @property Doctrine_Collection $GiacenzeProdotto
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProdotto extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('prodotto');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nome', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Giacenzaprodotto as GiacenzeProdotto', array(
             'local' => 'id',
             'foreign' => 'prodotto_id'));
    }
}