<?php

/**
 * AgenteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AgenteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AgenteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Agente');
    }
}