<?php

/**
 * AreaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AreaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AreaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Area');
    }
}