<?php

/**
 * AttivitaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AttivitaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AttivitaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Attivita');
    }
}