<?php

/**
 * GruppoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GruppoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GruppoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Gruppo');
    }
}