<?php

/**
 * ProvinciaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProvinciaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProvinciaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Provincia');
    }
}