<?php

/**
 * RegioneTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RegioneTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RegioneTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Regione');
    }
}