<?php

/**
 * TipoattivitaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoattivitaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoattivitaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tipoattivita');
    }
}