<?php

/**
 * Utente_GruppoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Utente_GruppoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Utente_GruppoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Utente_Gruppo');
    }
}