<?php

/**
 * Agente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Agente extends BaseAgente
{
	/*
	 *restituisce un array popolato con le regioni assegnate all'agente. Ogni membro dell'array è un array
	 *del tipo (id=>nome)
	 *Id è l'id della regione. 
	 */
	public function getRegioni(){
	$q=Doctrine_Query::create()->
	 	 	select('DISTINCT re.nome as nome, re.id,pr.id as id,pr.id,fa.id' )->
	 	 	from('Regione re')->
	 	 	leftjoin('re.Province pr')->
	 	 	leftjoin('pr.Farmacie fa')->
	 	 	where('fa.agente_id=?',$this->id)->
			orderBy('re.nome');
		if(!$r=$q->fetchArray()){
			return array();
		}
		foreach($r as $re){
			$result[$re['id']]=$re['nome'];
		}
		return $result;
	}
	/*
	 *restituisce un array popolato con le province assegnate all'agente. Ogni membro dell'array è un array
	 *del tipo (id=>nome)
	 *Id è la sigla della provincia
	 */
	public function getProvince(){
 	 	$q=Doctrine_Query::create()->
	 	 	select(' pr.nome as nome, pr.id as id,pr.id,fa.id' )->
	 	 	from('Provincia pr')->
	 	 	leftjoin('pr.Farmacie fa')->
	 	 	where('fa.agente_id=?',$this->id)->
			orderBy('pr.nome');
		if(!$r=$q->execute(array(),Doctrine_Core::HYDRATE_ARRAY)){
			return array();
		}
		foreach($r as $pr){
			$result[$pr['id']]=$pr['nome'];
		}
		return $result;
	}
	

	/*
	/*
	 *restituisce un array popolato con gli advisor delle microaree assegnate all'agente. Ogni membro dell'array è un array
	 *del tipo ('nome'=>'descrizione microarea','id'=>1300 )
	 *Id è il codice dell'advisor e nome è il suo nome e cognome reali. 
	 *
	public function getAdvisors(){
		$q=Doctrine_Query::create()->
 			select('DISTINCT ut.nome_completo as nome, ad.id as id' )->
			from('Agente ag')->
			leftjoin('ag.Advisors ad')->
			leftjoin('ad.Utente ut')->
			where('ag.id=?',$this->id)->
			orderBy('ut.nome_completo');
	return $q->fetchArray();
	}*/
	public function getAdvisors(){
		$q=Doctrine_Query::create()->
			select('ad.id,adut.nome_completo,ag.id,agut.nome_completo,adut.id')->
			from('Agente ag')->
			leftjoin('ag.Utente agut')->
			leftjoin('ag.Advisors ad')->
			leftjoin('ad.Utente adut')->
			where('ag.id=?',$this->id);
		if(!$r=$q->fetchArray()){
			return array();
		}
		$result=array();
		foreach ($r[0]['Advisors'] as $ad){
			$result[$ad['id']]=$ad['Utente']['nome_completo'];
		}
		return $result;
	}
	
	
	

}