<?php

/**
 * AttivitaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AttivitaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AttivitaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Attivita');
    }
    
    public function getAttivitaFarmacia($idFarmacia){
    	$q=$this->createQuery()->
    		select('a.id, a.giorno, a.ora_inizio, a.tipoattivita_id, t.nome as nome, a.stato,te.nome as campagna,
    		a.farmacia_id, a.data_chiusura, a.tipoevento_id, a.deleted_at, a.created_at, a.updated_at')
    		->from('Attivita a')
    		->leftjoin('a.Tipoattivita t')
    		->leftjoin('a.Tipoevento te')
    		->where('a.farmacia_id = ?',$idFarmacia)
    		->andWhere('a.deleted_at is null')
    		->orderBy('a.giorno');
    	return $q->execute(array(),Doctrine_Core::HYDRATE_ARRAY);
    }
    


    public function getAttivitaPerGiornoPerAdvisor($giorno,$advisor_id){
    	$q=$this->createQuery()->
    		select('at.id,at.ora_inizio as inizio,at.deleted_at as cancellato, t.nome as nome, f.denominazione as denominazione,
    			at.created_at,updated_at,f.id')->
    		from('attivita at')->
    		leftjoin('at.Farmacia f')->
    		leftjoin('at.Tipoattivita t')->
    		where('at.giorno = ?',$giorno)->
    		andWhere('at.deleted_at is null')->
    		andWhere('f.advisor_id = ?',$advisor_id);
    	return $q->fetchArray();
    }
    
public function getGiorniAttivitaAdvisorPeriodo($idAdvisor,$inizio,$fine){
    	$q=Doctrine_Core::getTable('Attivita')->createQuery()->
    		select( 'a.giorno , sum(t.impegno) as occupazione')->
    		from('Attivita a')->
    		leftjoin('a.Tipoattivita t')->
    		leftjoin('a.Farmacia f')->
    		where('f.advisor_id =?',$idAdvisor)->
    		andWhere('a.giorno >= ?',$inizio)->
    		andWhere('a.giorno <= ?',$fine)->
    		andWhere('a.deleted_at is null')->
    		groupBy('a.giorno')->
    		orderBy('a.giorno');
    		$a=$q->execute()->toArray();
    	return $a;
    }
	public function getEventiFuturi(){
	$q=Doctrine_Core::getTable('Attivita')->createQuery()->
		select('f.id as id,f.denominazione as denominazione ,f.indirizzo as indirizzo,f.cap as cap,f.localita as localita,f.provincia_id as provincia,
		f.numtel as numtel,f.numfax as numfax,f.email as email,f.isf as isf,utag.nome_completo as agente,
		utad.nome_completo as advisor, a.giorno as giorno,t.nome as evento,f.id,a.id,t.id,ag.id,ad.id')->
		from('Attivita a')->
		leftjoin('a.Tipoevento t')->
		leftjoin('a.Farmacia f')->
		leftjoin('f.Advisor ad')->
		leftjoin('f.Agente ag')->
		leftjoin('ag.Utente utag')->
		leftjoin('ad.Utente utad')->
		where('a.tipoattivita_id=?',3)->
    	andWhere('a.deleted_at is null')->
		andWhere('a.giorno >?',date('Y-m-d'))->
		orderBy('giorno');
	$a=$q->execute(array(),Doctrine_Core::HYDRATE_ARRAY);
	return $a;
	}
}