<?php

/**
 * Farmacia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Farmacia extends BaseFarmacia
{
	public function getRichiesteEventiAgente(){
		$q=Doctrine_Query::create()->
			select('f.id,r.*')->
			from('Farmacia f')->
			leftjoin('f.RichiesteTipoevento r')->
			where('f.id=?',$this->id)->
			andWhere('r.inserito_da_agente=true');
		$r=$q->execute();
		return $r[0]->RichiesteTipoevento;
	}

	public function getRichiesteEventiAdvisor(){
		$q=Doctrine_Query::create()->
			select('f.id,r.*')->
			from('Farmacia f')->
			leftjoin('f.RichiesteTipoevento r')->
			where('f.id=?',$this->id)->
			andWhere('r.inserito_da_agente=false');
		$r=$q->execute();
		return $r[0]->RichiesteTipoevento;
	}
}