<?php

/**
 * RegioneTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RegioneTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RegioneTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Regione');
    }
    
    //Restituisce un array di array (id,nome) 
    public function elencoRidotto(){
    	$q=$this->createQuery()->
    		select('id, nome')->
    		orderBy('nome');
    	$r=$q->fetchArray();
    	foreach($r as $re){
    		$result[$re['id']]=$re['nome'];
    	}
    	return $result;
    }
    
    public function statisticheRegionali(){
		$q=Doctrine_Query::create()->
    		select('re.id,re.nome, COUNT(fa.id) as numero')->
    		from('Regione re')->
    		leftjoin('re.Province pr')->
    		innerjoin('pr.Farmacie fa')->
    		groupBy('re.nome')->
    		orderBy('re.nome');
    	$r1=$q->execute(array(),Doctrine_Core::HYDRATE_ARRAY);


    		$q=Doctrine_Query::create()->
    			select('re.id,re.nome, COUNT(fa.id) as attive_ag')->
    			from('Regione re')->
    			leftjoin('re.Province pr')->
    			innerJoin('pr.Farmacie f')->
    			leftJoin('f.Farmacie_attivate_agente_view fa')->
    			groupBy('re.nome')->
    			orderBy('re.nome');
    		$r2=$q->execute(array(),Doctrine_Core::HYDRATE_ARRAY);
    		$q=Doctrine_Query::create()->
    			select('re.id,re.nome, COUNT(fa.id) as attive_adv')->
    			from('Regione re')->
    			leftjoin('re.Province pr')->
    			innerJoin('pr.Farmacie f')->
    			leftJoin('f.Farmacie_attivate_advisor_view fa')->
    			groupBy('re.nome')->
    			orderBy('re.nome');
    		$r3=$q->execute(array(),Doctrine_Core::HYDRATE_ARRAY);
			$tipi=Doctrine_Core::getTable('Tipoevento')->findAll();
			foreach($tipi as $tipo){
	    		$q=Doctrine_Query::create()->
	    			select('re.id,re.nome, SUM(ad_'.$tipo->id.') as numero'.$tipo->id.',SUM(ag_'.$tipo->id.') as numero_ag_'.$tipo->id)->
	    			from('Regione re')->
	    			leftjoin('re.Province pr')->
	    			innerjoin('pr.Farmacie f')->
	    			leftJoin('f.Farmacie_attivate_agente_view fa')->
	    			leftjoin('fa.Eventi_'.$tipo->id.'_view ri')->
	    			groupBy('re.nome')->
	    			orderBy('re.nome');
			${'s'.$tipo->id}=$q->execute(array(),Doctrine_Core::HYDRATE_ARRAY);
				   $z=Doctrine_Query::create()->
	    			select('re.id,re.nome, SUM(ad_'.$tipo->id.') as numero_attadv'.$tipo->id)->
	    			from('Regione re')->
	    			leftjoin('re.Province pr')->
	    			innerjoin('pr.Farmacie f')->
	    			leftJoin('f.Farmacie_attivate_advisor_view fa')->
	    			leftjoin('fa.Eventi_'.$tipo->id.'_view ri')->
	    			groupBy('re.nome')->
	    			orderBy('re.nome');
			${'t'.$tipo->id}=$z->execute(array(),Doctrine_Core::HYDRATE_ARRAY);
			}	
		$r=array();
		foreach($r1 as $chiave => $valore){
			$r[$chiave]=$valore+$r2[$chiave]+$r3[$chiave];
			foreach($tipi as $tipo){
				$r[$chiave]=$r[$chiave]+${'s'.$tipo->id}[$chiave]+${'t'.$tipo->id}[$chiave];
			}
		}
		return $r;
    }

    public function statisticheNazionali(){
    	$result=array();
		$q=Doctrine_Query::create()->
    		select('COUNT(fa.id) as numero')->
    		from('Regione re')->
    		leftjoin('re.Province pr')->
    		innerjoin('pr.Farmacie fa');
    	$r1=$q->execute(array(),Doctrine_Core::HYDRATE_ARRAY);
		$result['nome']='Italia';
		$result['numero']=$r1[0]['numero'];
    	$q=Doctrine_Query::create()->
    		select('COUNT(fa.id) as attive_ag')->
    		from('Regione re')->
    		leftjoin('re.Province pr')->
    		innerJoin('pr.Farmacie f')->
    		leftJoin('f.Farmacie_attivate_agente_view fa');
    	$r2=$q->execute(array(),Doctrine_Core::HYDRATE_ARRAY);
    	$result['attive_ag']=$r2[0]['attive_ag'];
    	$q=Doctrine_Query::create()->
    		select('COUNT(fa.id) as attive_adv')->
    		from('Regione re')->
    		leftjoin('re.Province pr')->
    		innerJoin('pr.Farmacie f')->
    		leftJoin('f.Farmacie_attivate_advisor_view fa');
    	$r3=$q->execute(array(),Doctrine_Core::HYDRATE_ARRAY);
    	$result['attive_adv']=$r3[0]['attive_adv'];
		$tipi=Doctrine_Core::getTable('Tipoevento')->findAll();
		foreach($tipi as $tipo){
	    	$q=Doctrine_Query::create()->
	    		select('SUM(ad_'.$tipo->id.') as numero'.$tipo->id.',SUM(ag_'.$tipo->id.') as numero_ag_'.$tipo->id)->
	    		from('Regione re')->
	    		leftjoin('re.Province pr')->
	    		innerjoin('pr.Farmacie f')->
	    		leftJoin('f.Farmacie_attivate_agente_view fa')->
	    		leftjoin('fa.Eventi_'.$tipo->id.'_view ri');
	    	$t=$q->execute(array(),Doctrine_Core::HYDRATE_ARRAY);
	    	$result['numero'.$tipo->id]=$t[0]['numero'.$tipo->id];
	    	$result['numero_ag_'.$tipo->id]=$t[0]['numero_ag_'.$tipo->id];
	    	$z=Doctrine_Query::create()->
	    		select('SUM(ad_'.$tipo->id.') as numero_attadv'.$tipo->id)->
	    		from('Regione re')->
	    		leftjoin('re.Province pr')->
	    		innerjoin('pr.Farmacie f')->
	    		leftJoin('f.Farmacie_attivate_advisor_view fa')->
	    		leftjoin('fa.Eventi_'.$tipo->id.'_view ri');
	    	$w=$z->execute(array(),Doctrine_Core::HYDRATE_ARRAY);
	    	$result['numero_attadv'.$tipo->id]=$w[0]['numero_attadv'.$tipo->id];
			}	
		return $result;
    }
 
}